### ISSUE TITLE
What license for this library?

### ISSUE THREAD

**Issue by KingjZhang** [lijundacom/AndroidRTSPLib2#1]
What license for this library?

这个库非常好,截获屏幕当成RTSP服务器,那能上传RTSP服务器吗?
没有添加Licenese文件呀,还是要问下什么许可呀.谢谢.

**Comment by lijundacom** [comment]
感谢您对这个库的关注。
目前没有上传功能。
已经增加了MIT许可。
这是我的联系方式。QQ：1187063889。如果有问题，可以随时联系我。

**Comment by wangse** [comment]
我想问一下，用android端录制的屏幕，PC端使用VLC软件点播，感觉很慢，很卡，过了一分钟就崩溃了，这个是什么问题
