### ISSUE TITLE
项目有报错

### ISSUE THREAD

**Issue by cl1069573062** [lijundacom/AndroidRTSPLib2#4]
mPort = mSession.getOriginPort();
     mServer = new ServerSocket(mPort); 会报在networkonMainThread.
而且弹出来myLibStreaming将开始截取屏幕上的所有内容点击立即开始后，项目就退出了。

**Comment by lijundacom** [comment]
试试clean project 然后重新编译安装。我没遇到报错的问题。但是遇到过项目退出的问题。一般是程序刚安装时需要四次赋权限操作。如果没赋权限，运行时会出现退出。
