### ISSUE TITLE
连接其他手机异常

### ISSUE THREAD

**Issue by carmindy** [lijundacom/AndroidRTSPLib2#5]
在其他手机登陆VLC 设置rtsp地址之后连接不上 请问咋回事呢

**Comment by lijundacom** [comment]
检查是否在同一局域网下？地址为服务器端地址，端口号自己设，程序默认为1234.
clean project 重新编译安装运行，看看有没有效果。如果有播放器链接，log信息中会显示链接信息。如果log中没有链接信息。说明网络有问题，可能不在同一局域网下。

03-02 11:21:24.197 31362-31667/com.example.ljd.mylibstreaming V/RtspServer: 新的客户端连接
03-02 11:21:24.199 31362-31769/com.example.ljd.mylibstreaming I/RtspServer: Connection from 192.168.1.59
03-02 11:21:24.242 31362-31769/com.example.ljd.mylibstreaming E/RtspServer: OPTIONS rtsp://192.168.1.21:1234/screen
03-02 11:21:24.243 31362-31769/com.example.ljd.mylibstreaming I/RtspServer: 进行OPTIONS
03-02 11:21:24.245 31362-31769/com.example.ljd.mylibstreaming D/RtspServer: RTSP/1.0 200 OK
                                                                            Server: ljd RTSP Server
                                                                            Cseq: 2
                                                                            Content-Length: 0
                                                                            Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE
                                                                            ... ...
