### ISSUE TITLE
画面花屏

### ISSUE THREAD

**Issue by bichao1986** [lijundacom/AndroidRTSPLib2#6]
当我通过手机运行程序录屏，然后通过电脑的VLC播放器去播放的时候，如果是在手机上播放一个视频的话，VLC播放器可以很顺畅的播放。如果是手机滑动屏幕或者去操作屏幕的软件，VLC就会花屏并且很容易就断开了，请问大神这一块的逻辑主要在哪里，我自己可以试着改改

**Comment by lijundacom** [comment]
app\src\main\java\com\example\ljd\mylibstreaming\LibRTSP\encorder\video\H264Encorder.java里的mMediaProjection.createVirtualDisplay。我获取屏幕信息的方式是使用MediaProjection。花屏是MediaProjection的固有缺陷。如果想不花屏的话，得使用其他方式获取屏幕数据，比如root后从系统C++层获取。

**Comment by bichao1986** [comment]
现在市面上有一个一款软件叫乐播，不知道大神是不是用过这一款软件，他在电视上装了一个乐播的服务端，然后同屏还算是比较流畅的。另外您说的那个花屏是MediaProjection的固有缺陷，但是我发现，通过MediaProjection录屏保存在本地的mp4文件还是很流畅的，您说的是他在传流数据的时候数据不完整么

**Comment by lijundacom** [comment]
我使用MediaProjection保存到本地mp4时，画面有些失真，效果比网络传输好。之前使用过SRC屏幕录像这款软件，这款软件是底层机制录屏的，很清晰，我的效果和他的没法比。

**Comment by bichao1986** [comment]
您写的已经非常牛逼了大神，您看我方便单独加您的联系方式么

**Comment by lijundacom** [comment]
好的，我QQ:1187063889。我不是什么大神:-D。只是我短期内可能不再维护这个这个项目了，能帮到你的有限。
